Repository Kernel360/hackerthon1-ministory, pull requests merged in 2023-10, with the labels that each got.

#9 add: update entity and repository info
  ministory/src/main/java/com/example/ministory/MinistoryApplication.java
  ministory/src/main/java/com/example/ministory/controller/UserApiController.java
  ministory/src/main/java/com/example/ministory/entity/CategoryEntity.java
  ministory/src/main/java/com/example/ministory/entity/PostEntity.java
  ministory/src/main/java/com/example/ministory/entity/UserEntity.java
  ministory/src/main/java/com/example/ministory/repository/CategoryRepository.java
  ministory/src/main/java/com/example/ministory/repository/PostRepository.java
  ministory/src/main/java/com/example/ministory/repository/UserRepository.java
  ministory/src/main/resources/application.yaml
Labels: enhancement

#11 feat: 남은 Entity 설정
  ministory/src/main/java/com/example/ministory/controller/UserApiController.java
  ministory/src/main/java/com/example/ministory/entity/Category.java
  ministory/src/main/java/com/example/ministory/entity/Comment.java
  ministory/src/main/java/com/example/ministory/entity/Likes.java
  ministory/src/main/java/com/example/ministory/entity/Notify.java
  ministory/src/main/java/com/example/ministory/entity/Post.java
  ministory/src/main/java/com/example/ministory/entity/Scrap.java
  ministory/src/main/java/com/example/ministory/entity/User.java
  ministory/src/main/java/com/example/ministory/entity/UserEntity.java
  ministory/src/main/java/com/example/ministory/repository/CategoryRepository.java
  ministory/src/main/java/com/example/ministory/repository/PostRepository.java
  ministory/src/main/java/com/example/ministory/repository/UserRepository.java
  ministory/src/main/java/com/example/ministory/util/NotifyType.java
  ministory/src/main/java/com/example/ministory/util/NotifyTypeConverter.java
  ministory/src/main/resources/application.yaml
Labels: enhancement

#15 chore: Add Swagger Configuration
  README.md
  ministory/build.gradle
  ministory/src/main/java/com/example/ministory/config/SwaggerConfig.java
  ministory/src/main/resources/application.yaml
Labels: documentation

#23 hotfix: Change table name notification to notify
  ministory/testdata/create-table.sql
Labels: bug

#27 test : Test insert UserCreateForm to UserRepository #26
  ministory/src/main/java/com/example/ministory/controller/UserController.java
  ministory/src/main/java/com/example/ministory/dto/UserDto.java
  ministory/src/main/java/com/example/ministory/entity/User.java
  ministory/src/main/java/com/example/ministory/service/UserService.java
  ministory/src/main/resources/templates/userCreateForm.html
  ministory/src/main/resources/templates/userlist.html
Labels: test

#37 feat : comment add, update, delete #29
  ministory/src/main/java/com/example/ministory/controller/UserController.java
  ministory/src/main/java/com/example/ministory/dto/CommentDto.java
  ministory/src/main/java/com/example/ministory/entity/Comment.java
  ministory/src/main/java/com/example/ministory/repository/CommentRepository.java
  ministory/src/main/java/com/example/ministory/service/CommentService.java
Labels: feat

#44 feat: Add CRUD API for likes
  README.md
  img.png
  ministory/src/main/java/com/example/ministory/controller/LikeController.java
  ministory/src/main/java/com/example/ministory/controller/ScrapController.java
  ministory/src/main/java/com/example/ministory/controller/UserController.java
  ministory/src/main/java/com/example/ministory/dto/DeleteManyLikesDto.java
  ministory/src/main/java/com/example/ministory/dto/DeleteManyScrapDto.java
  ministory/src/main/java/com/example/ministory/dto/LikePostDto.java
  ministory/src/main/java/com/example/ministory/dto/LikesDto.java
  ministory/src/main/java/com/example/ministory/dto/ScrapDto.java
  ministory/src/main/java/com/example/ministory/dto/ScrapPostDto.java
  ministory/src/main/java/com/example/ministory/dto/UserIdDto.java
  ministory/src/main/java/com/example/ministory/entity/Likes.java
  ministory/src/main/java/com/example/ministory/entity/Scrap.java
  ministory/src/main/java/com/example/ministory/entity/User.java
  ministory/src/main/java/com/example/ministory/repository/LikeRepository.java
  ministory/src/main/java/com/example/ministory/repository/ScrapRepository.java
  ministory/src/main/java/com/example/ministory/service/LikeService.java
  ministory/src/main/java/com/example/ministory/service/ScrapService.java
  ministory/src/main/resources/application.yaml
Labels: enhancement

#45 feat: Post View feature update
  ministory/src/main/java/com/example/ministory/controller/PostController.java
  ministory/src/main/java/com/example/ministory/controller/UserController.java
  ministory/src/main/java/com/example/ministory/service/PostService.java
  ministory/src/main/resources/templates/post/viewForm.html
  ministory/src/main/resources/templates/userCreateForm.html
Labels: enhancement

#46 refactor : add methods to comment feature
  ministory/src/main/java/com/example/ministory/controller/CommentController.java
  ministory/src/main/java/com/example/ministory/controller/UserController.java
  ministory/src/main/java/com/example/ministory/entity/Comment.java
  ministory/src/main/java/com/example/ministory/repository/CommentRepository.java
  ministory/src/main/java/com/example/ministory/service/CommentService.java
  ministory/src/main/resources/templates/comment/commentForm.html
  ministory/src/main/resources/templates/fragments/detailPostView.html
  ministory/src/main/resources/templates/layout/defaultLayout.html
  ministory/src/main/resources/templates/layout/postLayout.html
  ministory/src/main/resources/templates/test/commentViewTest.html
  ministory/src/main/resources/templates/test/commentWriteTest.html
  ministory/src/main/resources/templates/userCreateForm.html
Labels: feat

#52 feat: Add swagger config
  ministory/build.gradle
  ministory/src/main/java/com/example/ministory/config/SwaggerConfig.java
  ministory/src/main/java/com/example/ministory/controller/LikeController.java
  ministory/src/main/java/com/example/ministory/controller/ScrapController.java
  ministory/src/main/java/com/example/ministory/dto/LikesDto.java
  ministory/src/main/java/com/example/ministory/dto/ScrapDto.java
  ministory/src/main/java/com/example/ministory/service/PostService.java
  ministory/src/main/java/com/example/ministory/service/ScrapService.java
  ministory/src/main/resources/application.yaml
Labels: documentation

#63 feat: 내 블로그 메인 페이지 구현
  ministory/src/main/java/com/example/ministory/controller/PostController.java
  ministory/src/main/java/com/example/ministory/dto/PostDto.java
  ministory/src/main/java/com/example/ministory/repository/PostRepository.java
  ministory/src/main/java/com/example/ministory/service/PostService.java
  ministory/src/main/resources/templates/myBlog.html
  ministory/testdata/like-scrap-test-data.sql
Labels: feat

#67 fix: 좋아요/스크랩 모아보기 페이지 수정
  ministory/src/main/java/com/example/ministory/controller/LikeController.java
  ministory/src/main/java/com/example/ministory/controller/PostController.java
  ministory/src/main/java/com/example/ministory/controller/ScrapController.java
  ministory/src/main/java/com/example/ministory/service/LikeService.java
  ministory/src/main/java/com/example/ministory/service/ScrapService.java
  ministory/src/main/resources/application.yaml
  ministory/src/main/resources/templates/myLikes.html
  ministory/src/main/resources/templates/myScraps.html
Labels: feat

#69 feat: 메인페이지 구현 및 내비게이션 바 경로 설정
  ministory/src/main/java/com/example/ministory/controller/PostController.java
  ministory/src/main/java/com/example/ministory/service/PostService.java
  ministory/src/main/resources/application.yaml
  ministory/src/main/resources/templates/fragments/navbar.html
  ministory/src/main/resources/templates/mainPage.html
  ministory/src/main/resources/templates/myBlog.html
Labels: feat
